# permissions for end users to edit hyperippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperippool-editor-role
rules:
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hyperippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hyperippools/status
  verbs:
  - get
