# permissions for end users to view hypermachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypermachinepool-viewer-role
rules:
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hypermachinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hypermachinepools/status
  verbs:
  - get
