# permissions for end users to view hyperippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperippool-viewer-role
rules:
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hyperippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exp.infrastructure.cluster.x-k8s.io
  resources:
  - hyperippools/status
  verbs:
  - get
