# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/exp.infrastructure.cluster.x-k8s.io_hypermachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_hyperclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_hypermachines.yaml
- bases/infrastructure.cluster.x-k8s.io_hypermachinetemplates.yaml
- bases/exp.infrastructure.cluster.x-k8s.io_hyperippools.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_hypermachinepools.yaml
#- patches/webhook_in_hyperclusters.yaml
#- patches/webhook_in_hypermachines.yaml
#- patches/webhook_in_hypermachinetemplates.yaml
#- patches/webhook_in_hyperippools.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_hypermachinepools.yaml
#- patches/cainjection_in_hyperclusters.yaml
#- patches/cainjection_in_hypermachines.yaml
#- patches/cainjection_in_hypermachinetemplates.yaml
#- patches/cainjection_in_hyperippools.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
